config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
    resources :likes, only: [:create]
      resources :comments, only: [:new, :create] 
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comment_count

  def update_comment_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :increment_likes_counter

  def increment_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'must be an integer' }

  after_save :increment_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
# app/models/user.rb

class User < ApplicationRecord
  has_many :posts

  def most_recent_posts
    posts.order(created_at: :desc).limit(5) # Adjust the order and limit as needed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user
  before_action :set_post
  before_action :set_comment, only: [:show]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = current_user.comments.build(comment_params.merge(post: @post))
    if @comment.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to user_post_path(@post.author, @post), notice: 'Comment updated successfully'
    else
      render :edit
    end
  end

  def show
    @comments = @post.comments
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post, only: %i[new create]
  before_action :set_user
  before_action :set_post
  before_action :set_like, only: [:destroy]

  def new
    @like = @post.likes.new
  end

  def create
    @like = @post.likes.new(user: current_user)

    if @like.save
      redirect_to user_post_path(@post.author, @post), notice: 'Post liked!'
    else
      render :new
    end
  end

  def destroy
    @like.destroy
    redirect_to user_post_path(@post.author, @post)
  end

  private

  def set_like
    @like = @post.likes.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:post_id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  before_action :initialize_like

  def new
    @user = User.find(params[:user_id])
    @post = Post.build
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 6)
  end

  def show
    @user = User.find_by_id(params[:user_id])
    @post = Post.find_by_id(params[:id])
    @like = @post.likes
    @comments = @post.comments
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def initialize_like
    @like = Like.new
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      @recent_posts = @user.most_recent_posts
    else
      flash[:alert] = 'User not found'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/comment.html.erb
<div class="comment-container">
<h3>Add a new Comment</h3>
</div>

app/views/comments/new.html.erb
<div class="comment-container">
<h3>Add a new Comment</h3>
<div class="comment-form">
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path do |f| %>
<div>
<%= f.label :text, required: true%>
<%= f.text_field :text, required: true %>
</div>
<%= f.submit "Submit" %>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
   
   <body>
      <div id = "container">
        <%= yield -%>
      </div>
 
   </body>
</html>

app/views/likes/_like_action.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: post.author_id), data: { turbo: false }, local: true, scope: :like do |f| %>

<div>
  <%= f.hidden_field :user_id, value :user_id %>
  <%= f.hidden_field :post_id, value :post_id %>
  <%= f.submit "Like this post" %>
</div>

<% end %>

app/views/likes/like.html.erb
<% stylesheet_link_tag('index')%>
<div class="likes-container">
<button class="Add-likes">Like comment/post</button>
<div class="comment-form">
</div>
</div>

app/views/posts/_post_info.html.erb
<h3><%= post.title %></h3>

<p><%= post.text %></p>

<p class="counter">
  Comments: <%= post.comments_counter.to_i %>, Likes: <%= post.likes_counter.to_i %>
</p>

app/views/posts/_user_details.html.erb
<div class="user">
  <div class="user-photo">
    <%= image_tag(user.photo, alt: user.name, class: "photo") %>
  </div>
  <div class="user-details">
    <h1><%= link_to user.name, user_path(user) %></h1>
    <span>No of Posts: <%= user.posts.count %></span>
  </div>
</div>

app/views/posts/index.html.erb
<!-- Placeholder for index -->
<div class="main">
  <h1>List of all users:</h1>
  <% @users.each do |user| %>
    <%= render partial: 'users/user_details', locals: { user: user } %>
  <% end %>
</div>

app/views/posts/show.html.erb
<!-- Placeholder for show -->
<div>      
  <div class="user">
    <div class= "user-photo">
      <%= image_tag(@user.photo, alt: @user.name, class: "photo") %>
      </div>
      <div class="user-details">
        <h1><%= @user.name %></h1>
        <span>No of Posts: <%= @user.posts.count %></span>
      </div>
    </div>
    <button><%= link_to 'Back to Users List', users_path %></button>
  <div class=bio>
    <h2>Bio:</h2>
    <p><%= @user.bio %></p>

  </div>
  <div >
    <% @user.recent_posts.each do |post| %>
      <% @post = post %>
     <div class= "user-posts">
     <h2><%= link_to "#{post.title}", user_post_path(@user, post) %>
      </h2>
      <p><%= post.text %></p>
      <p class= "comments-likes">Comments: <%= post.comments.count %>, Likes: <%= post.likes.count %> </p>
    </div>   
    <% end %>
  </div>
  <div class="all-posts-button">
    <%= link_to "See all posts", user_posts_path(@user) %>
  </div>
</div>

app/views/shared/_comments.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.user.name%> :<%= comment.text %></p>
    </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="post">
<%=link_to user_post_path(user, post) do %>
<div class="single-post-cont">
<div class="post-title">
<h1><%= post.title %></h1>
</div>
<div class="post-content">
<p><%= post.text %></p>
</div>
<div class="interactions">
<p>comments: <%= post.comments_counter %></p>
<p>likes: <%= post.likes_counter %></p>
</div>
</div>
<% end %>
</div>

app/views/shared/_user.html.erb
<div class="user-container">
<%=link_to user_path(user) do %>
<div class="container-components">
<div class="img-container">
<img src="<%= user.photo_link %>"
alt="<%= user.name %>" />
</div>
<div class="userpost-container">
<h1 class="user-name"><%= user.name %></h1>
<p class="user-post">Number of posts: <%= user.posts_counter %></p>
</div>
</div>
<% end %>

</div>

app/views/users/_user_info.html.erb
<img src=<%= user.photo %> id="user-photo" alt="a_user">
<div id="user-text">
  <h2><%= user.name %></h2><br>
  <p>Number of posts: <%= user.posts_counter.to_i %></p>
</div>

app/views/users/index.html.erb
<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="show-page">
  <div class="users">
    <%= render 'shared/user', user: @user %>
  </div>
  <div class="posts">
    <h2>Recent Posts</h2>
    <% if @recent_posts.present? %>
      <% @recent_posts.each do |post| %>
        <%= render 'shared/post', post: post, user: @user %>
      <% end %>
    <% else %>
      <p>No recent posts available.</p>
    <% end %>
  </div>
  <%= link_to 'See all posts', user_posts_path(@user) %>
</div>